# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.setEnabled(True)
        Form.resize(885, 300)
        Form.setMinimumSize(QtCore.QSize(885, 300))
        Form.setMaximumSize(QtCore.QSize(1200, 620))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        Form.setFont(font)
        Form.setFocusPolicy(QtCore.Qt.NoFocus)
        Form.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Form.setAcceptDrops(False)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_save = QtWidgets.QPushButton(Form)
        self.pushButton_save.setGeometry(QtCore.QRect(310, 230, 100, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}\n"
"QPushButton{color: rgb(0, 0, 0);}")
        self.pushButton_save.setObjectName("pushButton_save")
        self.pushButton_default = QtWidgets.QPushButton(Form)
        self.pushButton_default.setGeometry(QtCore.QRect(480, 230, 100, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.pushButton_default.setFont(font)
        self.pushButton_default.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}\n"
"QPushButton{color: rgb(0, 0, 0);}")
        self.pushButton_default.setObjectName("pushButton_default")
        self.pushButton_set = QtWidgets.QPushButton(Form)
        self.pushButton_set.setGeometry(QtCore.QRect(140, 230, 100, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.pushButton_set.setFont(font)
        self.pushButton_set.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}\n"
"QPushButton{color: rgb(0, 0, 0);}")
        self.pushButton_set.setObjectName("pushButton_set")
        self.pushButton_quit = QtWidgets.QPushButton(Form)
        self.pushButton_quit.setGeometry(QtCore.QRect(650, 230, 100, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.pushButton_quit.setFont(font)
        self.pushButton_quit.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.pushButton_quit.setObjectName("pushButton_quit")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(10, 20, 281, 201))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.splitter_17 = QtWidgets.QSplitter(self.frame)
        self.splitter_17.setGeometry(QtCore.QRect(10, 50, 260, 67))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.splitter_17.setFont(font)
        self.splitter_17.setOrientation(QtCore.Qt.Vertical)
        self.splitter_17.setObjectName("splitter_17")
        self.splitter_5 = QtWidgets.QSplitter(self.splitter_17)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.doubleSpinBox_high_speed_forward_offset = QtWidgets.QDoubleSpinBox(self.splitter_5)
        self.doubleSpinBox_high_speed_forward_offset.setMinimumSize(QtCore.QSize(80, 0))
        self.doubleSpinBox_high_speed_forward_offset.setMaximumSize(QtCore.QSize(80, 16777215))
        self.doubleSpinBox_high_speed_forward_offset.setSizeIncrement(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox_high_speed_forward_offset.setFont(font)
        self.doubleSpinBox_high_speed_forward_offset.setDecimals(2)
        self.doubleSpinBox_high_speed_forward_offset.setMinimum(-5.0)
        self.doubleSpinBox_high_speed_forward_offset.setMaximum(5.0)
        self.doubleSpinBox_high_speed_forward_offset.setSingleStep(0.1)
        self.doubleSpinBox_high_speed_forward_offset.setObjectName("doubleSpinBox_high_speed_forward_offset")
        self.label_9 = QtWidgets.QLabel(self.splitter_5)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.splitter_6 = QtWidgets.QSplitter(self.splitter_17)
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName("splitter_6")
        self.doubleSpinBox_high_speed_backward_offset = QtWidgets.QDoubleSpinBox(self.splitter_6)
        self.doubleSpinBox_high_speed_backward_offset.setMinimumSize(QtCore.QSize(80, 0))
        self.doubleSpinBox_high_speed_backward_offset.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox_high_speed_backward_offset.setFont(font)
        self.doubleSpinBox_high_speed_backward_offset.setDecimals(2)
        self.doubleSpinBox_high_speed_backward_offset.setMinimum(-5.0)
        self.doubleSpinBox_high_speed_backward_offset.setMaximum(5.0)
        self.doubleSpinBox_high_speed_backward_offset.setSingleStep(0.1)
        self.doubleSpinBox_high_speed_backward_offset.setObjectName("doubleSpinBox_high_speed_backward_offset")
        self.label_10 = QtWidgets.QLabel(self.splitter_6)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.splitter_16 = QtWidgets.QSplitter(self.frame)
        self.splitter_16.setGeometry(QtCore.QRect(10, 123, 260, 67))
        self.splitter_16.setOrientation(QtCore.Qt.Vertical)
        self.splitter_16.setObjectName("splitter_16")
        self.splitter_12 = QtWidgets.QSplitter(self.splitter_16)
        self.splitter_12.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_12.setObjectName("splitter_12")
        self.doubleSpinBox_high_speed_move_right_offset = QtWidgets.QDoubleSpinBox(self.splitter_12)
        self.doubleSpinBox_high_speed_move_right_offset.setMinimumSize(QtCore.QSize(80, 0))
        self.doubleSpinBox_high_speed_move_right_offset.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox_high_speed_move_right_offset.setFont(font)
        self.doubleSpinBox_high_speed_move_right_offset.setDecimals(2)
        self.doubleSpinBox_high_speed_move_right_offset.setMinimum(-5.0)
        self.doubleSpinBox_high_speed_move_right_offset.setMaximum(5.0)
        self.doubleSpinBox_high_speed_move_right_offset.setSingleStep(0.1)
        self.doubleSpinBox_high_speed_move_right_offset.setObjectName("doubleSpinBox_high_speed_move_right_offset")
        self.label_17 = QtWidgets.QLabel(self.splitter_12)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.splitter_11 = QtWidgets.QSplitter(self.splitter_16)
        self.splitter_11.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_11.setObjectName("splitter_11")
        self.doubleSpinBox_high_speed_move_left_offset = QtWidgets.QDoubleSpinBox(self.splitter_11)
        self.doubleSpinBox_high_speed_move_left_offset.setMinimumSize(QtCore.QSize(80, 0))
        self.doubleSpinBox_high_speed_move_left_offset.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox_high_speed_move_left_offset.setFont(font)
        self.doubleSpinBox_high_speed_move_left_offset.setDecimals(2)
        self.doubleSpinBox_high_speed_move_left_offset.setMinimum(-5.0)
        self.doubleSpinBox_high_speed_move_left_offset.setMaximum(5.0)
        self.doubleSpinBox_high_speed_move_left_offset.setSingleStep(0.1)
        self.doubleSpinBox_high_speed_move_left_offset.setObjectName("doubleSpinBox_high_speed_move_left_offset")
        self.label_8 = QtWidgets.QLabel(self.splitter_11)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(120, 10, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(300, 20, 281, 201))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.splitter_18 = QtWidgets.QSplitter(self.frame_2)
        self.splitter_18.setGeometry(QtCore.QRect(10, 50, 260, 67))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.splitter_18.setFont(font)
        self.splitter_18.setOrientation(QtCore.Qt.Vertical)
        self.splitter_18.setObjectName("splitter_18")
        self.splitter_7 = QtWidgets.QSplitter(self.splitter_18)
        self.splitter_7.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_7.setObjectName("splitter_7")
        self.doubleSpinBox_medium_speed_forward_offset = QtWidgets.QDoubleSpinBox(self.splitter_7)
        self.doubleSpinBox_medium_speed_forward_offset.setMinimumSize(QtCore.QSize(80, 0))
        self.doubleSpinBox_medium_speed_forward_offset.setMaximumSize(QtCore.QSize(80, 16777215))
        self.doubleSpinBox_medium_speed_forward_offset.setSizeIncrement(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox_medium_speed_forward_offset.setFont(font)
        self.doubleSpinBox_medium_speed_forward_offset.setDecimals(2)
        self.doubleSpinBox_medium_speed_forward_offset.setMinimum(-5.0)
        self.doubleSpinBox_medium_speed_forward_offset.setMaximum(5.0)
        self.doubleSpinBox_medium_speed_forward_offset.setSingleStep(0.1)
        self.doubleSpinBox_medium_speed_forward_offset.setObjectName("doubleSpinBox_medium_speed_forward_offset")
        self.label_11 = QtWidgets.QLabel(self.splitter_7)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.splitter_8 = QtWidgets.QSplitter(self.splitter_18)
        self.splitter_8.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_8.setObjectName("splitter_8")
        self.doubleSpinBox_medium_speed_backward_offset = QtWidgets.QDoubleSpinBox(self.splitter_8)
        self.doubleSpinBox_medium_speed_backward_offset.setMinimumSize(QtCore.QSize(80, 0))
        self.doubleSpinBox_medium_speed_backward_offset.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox_medium_speed_backward_offset.setFont(font)
        self.doubleSpinBox_medium_speed_backward_offset.setDecimals(2)
        self.doubleSpinBox_medium_speed_backward_offset.setMinimum(-5.0)
        self.doubleSpinBox_medium_speed_backward_offset.setMaximum(5.0)
        self.doubleSpinBox_medium_speed_backward_offset.setSingleStep(0.1)
        self.doubleSpinBox_medium_speed_backward_offset.setObjectName("doubleSpinBox_medium_speed_backward_offset")
        self.label_12 = QtWidgets.QLabel(self.splitter_8)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.splitter_19 = QtWidgets.QSplitter(self.frame_2)
        self.splitter_19.setGeometry(QtCore.QRect(10, 123, 260, 67))
        self.splitter_19.setOrientation(QtCore.Qt.Vertical)
        self.splitter_19.setObjectName("splitter_19")
        self.splitter_13 = QtWidgets.QSplitter(self.splitter_19)
        self.splitter_13.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_13.setObjectName("splitter_13")
        self.doubleSpinBox_medium_speed_move_right_offset = QtWidgets.QDoubleSpinBox(self.splitter_13)
        self.doubleSpinBox_medium_speed_move_right_offset.setMinimumSize(QtCore.QSize(80, 0))
        self.doubleSpinBox_medium_speed_move_right_offset.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox_medium_speed_move_right_offset.setFont(font)
        self.doubleSpinBox_medium_speed_move_right_offset.setDecimals(2)
        self.doubleSpinBox_medium_speed_move_right_offset.setMinimum(-5.0)
        self.doubleSpinBox_medium_speed_move_right_offset.setMaximum(5.0)
        self.doubleSpinBox_medium_speed_move_right_offset.setSingleStep(0.1)
        self.doubleSpinBox_medium_speed_move_right_offset.setObjectName("doubleSpinBox_medium_speed_move_right_offset")
        self.label_18 = QtWidgets.QLabel(self.splitter_13)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.splitter_14 = QtWidgets.QSplitter(self.splitter_19)
        self.splitter_14.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_14.setObjectName("splitter_14")
        self.doubleSpinBox_medium_speed_move_left_offset = QtWidgets.QDoubleSpinBox(self.splitter_14)
        self.doubleSpinBox_medium_speed_move_left_offset.setMinimumSize(QtCore.QSize(80, 0))
        self.doubleSpinBox_medium_speed_move_left_offset.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox_medium_speed_move_left_offset.setFont(font)
        self.doubleSpinBox_medium_speed_move_left_offset.setDecimals(2)
        self.doubleSpinBox_medium_speed_move_left_offset.setMinimum(-5.0)
        self.doubleSpinBox_medium_speed_move_left_offset.setMaximum(5.0)
        self.doubleSpinBox_medium_speed_move_left_offset.setSingleStep(0.1)
        self.doubleSpinBox_medium_speed_move_left_offset.setObjectName("doubleSpinBox_medium_speed_move_left_offset")
        self.label_13 = QtWidgets.QLabel(self.splitter_14)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(120, 10, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(590, 20, 281, 201))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.splitter_20 = QtWidgets.QSplitter(self.frame_3)
        self.splitter_20.setGeometry(QtCore.QRect(10, 50, 260, 67))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.splitter_20.setFont(font)
        self.splitter_20.setOrientation(QtCore.Qt.Vertical)
        self.splitter_20.setObjectName("splitter_20")
        self.splitter_9 = QtWidgets.QSplitter(self.splitter_20)
        self.splitter_9.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_9.setObjectName("splitter_9")
        self.doubleSpinBox_low_speed_forward_offset = QtWidgets.QDoubleSpinBox(self.splitter_9)
        self.doubleSpinBox_low_speed_forward_offset.setMinimumSize(QtCore.QSize(80, 0))
        self.doubleSpinBox_low_speed_forward_offset.setMaximumSize(QtCore.QSize(80, 16777215))
        self.doubleSpinBox_low_speed_forward_offset.setSizeIncrement(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox_low_speed_forward_offset.setFont(font)
        self.doubleSpinBox_low_speed_forward_offset.setDecimals(2)
        self.doubleSpinBox_low_speed_forward_offset.setMinimum(-5.0)
        self.doubleSpinBox_low_speed_forward_offset.setMaximum(5.0)
        self.doubleSpinBox_low_speed_forward_offset.setSingleStep(0.1)
        self.doubleSpinBox_low_speed_forward_offset.setObjectName("doubleSpinBox_low_speed_forward_offset")
        self.label_14 = QtWidgets.QLabel(self.splitter_9)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.splitter_10 = QtWidgets.QSplitter(self.splitter_20)
        self.splitter_10.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_10.setObjectName("splitter_10")
        self.doubleSpinBox_low_speed_backward_offset = QtWidgets.QDoubleSpinBox(self.splitter_10)
        self.doubleSpinBox_low_speed_backward_offset.setMinimumSize(QtCore.QSize(80, 0))
        self.doubleSpinBox_low_speed_backward_offset.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox_low_speed_backward_offset.setFont(font)
        self.doubleSpinBox_low_speed_backward_offset.setDecimals(2)
        self.doubleSpinBox_low_speed_backward_offset.setMinimum(-5.0)
        self.doubleSpinBox_low_speed_backward_offset.setMaximum(5.0)
        self.doubleSpinBox_low_speed_backward_offset.setSingleStep(0.1)
        self.doubleSpinBox_low_speed_backward_offset.setObjectName("doubleSpinBox_low_speed_backward_offset")
        self.label_15 = QtWidgets.QLabel(self.splitter_10)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.splitter_21 = QtWidgets.QSplitter(self.frame_3)
        self.splitter_21.setGeometry(QtCore.QRect(10, 123, 260, 67))
        self.splitter_21.setOrientation(QtCore.Qt.Vertical)
        self.splitter_21.setObjectName("splitter_21")
        self.splitter_15 = QtWidgets.QSplitter(self.splitter_21)
        self.splitter_15.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_15.setObjectName("splitter_15")
        self.doubleSpinBox_low_speed_move_right_offset = QtWidgets.QDoubleSpinBox(self.splitter_15)
        self.doubleSpinBox_low_speed_move_right_offset.setMinimumSize(QtCore.QSize(80, 0))
        self.doubleSpinBox_low_speed_move_right_offset.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox_low_speed_move_right_offset.setFont(font)
        self.doubleSpinBox_low_speed_move_right_offset.setDecimals(2)
        self.doubleSpinBox_low_speed_move_right_offset.setMinimum(-5.0)
        self.doubleSpinBox_low_speed_move_right_offset.setMaximum(5.0)
        self.doubleSpinBox_low_speed_move_right_offset.setSingleStep(0.1)
        self.doubleSpinBox_low_speed_move_right_offset.setObjectName("doubleSpinBox_low_speed_move_right_offset")
        self.label_19 = QtWidgets.QLabel(self.splitter_15)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.splitter_22 = QtWidgets.QSplitter(self.splitter_21)
        self.splitter_22.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_22.setObjectName("splitter_22")
        self.doubleSpinBox_low_speed_move_left_offset = QtWidgets.QDoubleSpinBox(self.splitter_22)
        self.doubleSpinBox_low_speed_move_left_offset.setMinimumSize(QtCore.QSize(80, 0))
        self.doubleSpinBox_low_speed_move_left_offset.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.doubleSpinBox_low_speed_move_left_offset.setFont(font)
        self.doubleSpinBox_low_speed_move_left_offset.setDecimals(2)
        self.doubleSpinBox_low_speed_move_left_offset.setMinimum(-5.0)
        self.doubleSpinBox_low_speed_move_left_offset.setMaximum(5.0)
        self.doubleSpinBox_low_speed_move_left_offset.setSingleStep(0.1)
        self.doubleSpinBox_low_speed_move_left_offset.setObjectName("doubleSpinBox_low_speed_move_left_offset")
        self.label_16 = QtWidgets.QLabel(self.splitter_22)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(120, 10, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "adjustment tool 1.0"))
        self.pushButton_save.setText(_translate("Form", "保存"))
        self.pushButton_default.setText(_translate("Form", "重置"))
        self.pushButton_set.setText(_translate("Form", "应用"))
        self.pushButton_quit.setText(_translate("Form", "退出"))
        self.label_9.setText(_translate("Form", "前进偏移(正往左偏)"))
        self.label_10.setText(_translate("Form", "后退偏移(正往左偏)"))
        self.label_17.setText(_translate("Form", "右移偏移(正往左偏)"))
        self.label_8.setText(_translate("Form", "左移偏移(正往左偏)"))
        self.label.setText(_translate("Form", "高速"))
        self.label_11.setText(_translate("Form", "前进偏移(正往左偏)"))
        self.label_12.setText(_translate("Form", "后退偏移(正往左偏)"))
        self.label_18.setText(_translate("Form", "右移偏移(正往左偏)"))
        self.label_13.setText(_translate("Form", "左移偏移(正往左偏)"))
        self.label_2.setText(_translate("Form", "中速"))
        self.label_14.setText(_translate("Form", "前进偏移(正往左偏)"))
        self.label_15.setText(_translate("Form", "后退偏移(正往左偏)"))
        self.label_19.setText(_translate("Form", "右移偏移(正往左偏)"))
        self.label_16.setText(_translate("Form", "左移偏移(正往左偏)"))
        self.label_3.setText(_translate("Form", "低速"))
