high_speed_backward_offset: 0.6000000238418579
high_speed_forward_offset: 2.7755575615628914e-17
high_speed_move_left_offset: 1.2999999523162842
high_speed_move_right_offset: -0.4000000059604645
low_speed_backward_offset: 0.0
low_speed_forward_offset: 0.0
low_speed_move_left_offset: 0.0
low_speed_move_right_offset: 0.0
medium_speed_backward_offset: 0.0
medium_speed_forward_offset: 0.0
medium_speed_move_left_offset: 0.0
medium_speed_move_right_offset: 0.0
